// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_dashboard.sql

package db

import (
	"context"
	"time"
)

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*) AS count FROM users
`

func (q *Queries) AdminCountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountProducts = `-- name: AdminCountProducts :one
SELECT COUNT(*) AS count FROM products
`

func (q *Queries) AdminCountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountOrders = `-- name: AdminCountOrders :one
SELECT COUNT(*) AS count FROM orders
`

func (q *Queries) AdminCountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountOrdersByStatus = `-- name: AdminCountOrdersByStatus :one
SELECT COUNT(*) AS count FROM orders WHERE status = ?
`

func (q *Queries) AdminCountOrdersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountOrdersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminSumPaidAmount = `-- name: AdminSumPaidAmount :one
SELECT COALESCE(SUM(total_amount_minor), 0) AS total
FROM orders
WHERE status = 'paid'
`

func (q *Queries) AdminSumPaidAmount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminSumPaidAmount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const adminCountUsersToday = `-- name: AdminCountUsersToday :one
SELECT COUNT(*) AS count FROM users WHERE DATE(created_at) = CURDATE()
`

func (q *Queries) AdminCountUsersToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountUsersToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsersYesterday = `-- name: AdminCountUsersYesterday :one
SELECT COUNT(*) AS count FROM users WHERE DATE(created_at) = DATE_SUB(CURDATE(), INTERVAL 1 DAY)
`

func (q *Queries) AdminCountUsersYesterday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountUsersYesterday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountOrdersToday = `-- name: AdminCountOrdersToday :one
SELECT COUNT(*) AS count FROM orders WHERE DATE(created_at) = CURDATE()
`

func (q *Queries) AdminCountOrdersToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountOrdersToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountOrdersYesterday = `-- name: AdminCountOrdersYesterday :one
SELECT COUNT(*) AS count FROM orders WHERE DATE(created_at) = DATE_SUB(CURDATE(), INTERVAL 1 DAY)
`

func (q *Queries) AdminCountOrdersYesterday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountOrdersYesterday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminDailyNewUsers = `-- name: AdminDailyNewUsers :many
SELECT DATE(created_at) AS day, COUNT(*) AS count
FROM users
WHERE created_at >= DATE_SUB(CURDATE(), INTERVAL 6 DAY)
GROUP BY DATE(created_at)
ORDER BY day ASC
`

type AdminDailyNewUsersRow struct {
	Day   time.Time `json:"day"`
	Count int64     `json:"count"`
}

func (q *Queries) AdminDailyNewUsers(ctx context.Context) ([]AdminDailyNewUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminDailyNewUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminDailyNewUsersRow
	for rows.Next() {
		var i AdminDailyNewUsersRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminDailyNewOrders = `-- name: AdminDailyNewOrders :many
SELECT DATE(created_at) AS day, COUNT(*) AS count
FROM orders
WHERE created_at >= DATE_SUB(CURDATE(), INTERVAL 6 DAY)
GROUP BY DATE(created_at)
ORDER BY day ASC
`

type AdminDailyNewOrdersRow struct {
	Day   time.Time `json:"day"`
	Count int64     `json:"count"`
}

func (q *Queries) AdminDailyNewOrders(ctx context.Context) ([]AdminDailyNewOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminDailyNewOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminDailyNewOrdersRow
	for rows.Next() {
		var i AdminDailyNewOrdersRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminTopProductSales = `-- name: AdminTopProductSales :many
SELECT
  p.id AS product_id,
  p.title AS product_title,
  COALESCE(SUM(oi.quantity), 0) AS sales_qty
FROM order_items oi
JOIN products p ON p.id = oi.product_id
JOIN orders o ON o.id = oi.order_id
WHERE o.status = 'paid'
GROUP BY p.id, p.title
ORDER BY sales_qty DESC, p.id ASC
LIMIT 5
`

type AdminTopProductSalesRow struct {
	ProductID    uint64 `json:"product_id"`
	ProductTitle string `json:"product_title"`
	SalesQty     int64  `json:"sales_qty"`
}

func (q *Queries) AdminTopProductSales(ctx context.Context) ([]AdminTopProductSalesRow, error) {
	rows, err := q.db.QueryContext(ctx, adminTopProductSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminTopProductSalesRow
	for rows.Next() {
		var i AdminTopProductSalesRow
		if err := rows.Scan(&i.ProductID, &i.ProductTitle, &i.SalesQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
