// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package db

import (
	"context"
)

const getAdminByAccount = `-- name: GetAdminByAccount :one
SELECT id, account, nickname, password_hash, created_at FROM ` + "`" + `admin` + "`" + ` WHERE account = ? LIMIT 1
`

func (q *Queries) GetAdminByAccount(ctx context.Context, account string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByAccount, account)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Nickname,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, account, nickname, password_hash, created_at FROM ` + "`" + `admin` + "`" + ` WHERE id = ? LIMIT 1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uint64) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Nickname,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const adminUpdateNickname = `-- name: AdminUpdateNickname :exec
UPDATE ` + "`" + `admin` + "`" + ` SET nickname = ? WHERE id = ?
`

func (q *Queries) AdminUpdateNickname(ctx context.Context, nickname string, id uint64) error {
	_, err := q.db.ExecContext(ctx, adminUpdateNickname, nickname, id)
	return err
}

const adminUpdatePassword = `-- name: AdminUpdatePassword :exec
UPDATE ` + "`" + `admin` + "`" + ` SET password_hash = ? WHERE id = ?
`

func (q *Queries) AdminUpdatePassword(ctx context.Context, passwordHash string, id uint64) error {
	_, err := q.db.ExecContext(ctx, adminUpdatePassword, passwordHash, id)
	return err
}
