// Code generated by sqlc. DO NOT EDIT.
// source: business.sql

package db

import (
	"context"
)

const listBusinessBySection = `-- name: ListBusinessBySection :many
SELECT id, section_slug, title, description, sort_order, created_at, updated_at
FROM ` + "`" + `business` + "`" + `
WHERE section_slug = ?
ORDER BY id ASC
`

func (q *Queries) ListBusinessBySection(ctx context.Context, sectionSlug string) ([]Business, error) {
	rows, err := q.db.QueryContext(ctx, listBusinessBySection, sectionSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.SectionSlug,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
