// Code generated by sqlc. DO NOT EDIT.
// source: business_admin.sql

package db

import (
	"context"
	"database/sql"
)

const adminListBusiness = `-- name: AdminListBusiness :many
SELECT id, section_slug, title, description, sort_order, created_at, updated_at
FROM ` + "`" + `business` + "`" + `
ORDER BY id ASC
`

func (q *Queries) AdminListBusiness(ctx context.Context) ([]Business, error) {
	rows, err := q.db.QueryContext(ctx, adminListBusiness)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.SectionSlug,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListBusinessBySection = `-- name: AdminListBusinessBySection :many
SELECT id, section_slug, title, description, sort_order, created_at, updated_at
FROM ` + "`" + `business` + "`" + `
WHERE section_slug = ?
ORDER BY id ASC
`

func (q *Queries) AdminListBusinessBySection(ctx context.Context, sectionSlug string) ([]Business, error) {
	rows, err := q.db.QueryContext(ctx, adminListBusinessBySection, sectionSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.SectionSlug,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetBusinessByID = `-- name: AdminGetBusinessByID :one
SELECT id, section_slug, title, description, sort_order, created_at, updated_at
FROM ` + "`" + `business` + "`" + `
WHERE id = ?
LIMIT 1
`

func (q *Queries) AdminGetBusinessByID(ctx context.Context, id uint64) (Business, error) {
	row := q.db.QueryRowContext(ctx, adminGetBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.SectionSlug,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminCreateBusiness = `-- name: AdminCreateBusiness :execresult
INSERT INTO ` + "`" + `business` + "`" + ` (section_slug, title, description, sort_order)
VALUES (?, ?, ?, ?)
`

type AdminCreateBusinessParams struct {
	SectionSlug string `json:"section_slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	SortOrder   int32  `json:"sort_order"`
}

func (q *Queries) AdminCreateBusiness(ctx context.Context, arg AdminCreateBusinessParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, adminCreateBusiness,
		arg.SectionSlug,
		arg.Title,
		arg.Description,
		arg.SortOrder,
	)
}

const adminUpdateBusiness = `-- name: AdminUpdateBusiness :exec
UPDATE ` + "`" + `business` + "`" + `
SET section_slug = ?, title = ?, description = ?, sort_order = ?
WHERE id = ?
`

type AdminUpdateBusinessParams struct {
	SectionSlug string `json:"section_slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	SortOrder   int32  `json:"sort_order"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminUpdateBusiness(ctx context.Context, arg AdminUpdateBusinessParams) error {
	_, err := q.db.ExecContext(ctx, adminUpdateBusiness,
		arg.SectionSlug,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const adminDeleteBusiness = `-- name: AdminDeleteBusiness :exec
DELETE FROM ` + "`" + `business` + "`" + `
WHERE id = ?
`

func (q *Queries) AdminDeleteBusiness(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, adminDeleteBusiness, id)
	return err
}
