// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: downloads.sql

package db

import (
	"context"
)

const userOwnsPaidProduct = `-- name: UserOwnsPaidProduct :one
SELECT EXISTS(
  SELECT 1
  FROM order_items oi
  INNER JOIN orders o ON o.id = oi.order_id
  WHERE o.user_id = ? AND oi.product_id = ? AND o.status = 'paid'
) AS owned
`

type UserOwnsPaidProductParams struct {
	UserID    uint64 `json:"user_id"`
	ProductID uint64 `json:"product_id"`
}

func (q *Queries) UserOwnsPaidProduct(ctx context.Context, arg UserOwnsPaidProductParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userOwnsPaidProduct, arg.UserID, arg.ProductID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}
