// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID           uint64    `json:"id"`
	Account      string    `json:"account"`
	Nickname     string    `json:"nickname"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type Product struct {
	ID          uint64         `json:"id"`
	Slug        string         `json:"slug"`
	Category    string         `json:"category"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	PriceMinor  int64          `json:"price_minor"`
	Currency    string         `json:"currency"`
	ImageUrl     sql.NullString `json:"image_url"`
	PreviewUrl   sql.NullString `json:"preview_url"`
	DownloadUrl  sql.NullString `json:"download_url"`
	SortOrder    int32          `json:"sort_order"`
	Recommended bool           `json:"recommended"`
	Visible     bool           `json:"visible"`
	Downloads   int64          `json:"downloads"`
	Score       float64        `json:"score"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Business struct {
	ID          uint64    `json:"id"`
	SectionSlug string    `json:"section_slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	SortOrder   int32     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID           uint64    `json:"id"`
	UserNo       string    `json:"user_no"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type Order struct {
	ID               uint64    `json:"id"`
	UserID           uint64    `json:"user_id"`
	Status           string    `json:"status"`
	TotalAmountMinor int64     `json:"total_amount_minor"`
	Currency         string    `json:"currency"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type OrderItem struct {
	ID             uint64    `json:"id"`
	OrderID        uint64    `json:"order_id"`
	ProductID      uint64    `json:"product_id"`
	Quantity       uint32    `json:"quantity"`
	UnitPriceMinor int64     `json:"unit_price_minor"`
	CreatedAt      time.Time `json:"created_at"`
}
