// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders_admin.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const adminListOrders = `-- name: AdminListOrders :many
SELECT
  o.id,
  o.order_no,
  o.user_id,
  u.email AS user_email,
  o.status,
  o.total_amount_minor,
  o.currency,
  o.created_at,
  o.updated_at,
  COUNT(oi.id) AS item_count,
  GROUP_CONCAT(
    CONCAT(p.title, IF(oi.quantity > 1, CONCAT(' ×', oi.quantity), ''))
    ORDER BY oi.id
    SEPARATOR '、'
  ) AS items_summary
FROM orders o
INNER JOIN users u ON u.id = o.user_id
LEFT JOIN order_items oi ON oi.order_id = o.id
LEFT JOIN products p ON p.id = oi.product_id
GROUP BY o.id, o.order_no, o.user_id, u.email, o.status, o.total_amount_minor, o.currency, o.created_at, o.updated_at
ORDER BY o.created_at DESC, o.id DESC
`

type AdminListOrdersRow struct {
	ID               uint64         `json:"id"`
	OrderNo          string         `json:"order_no"`
	UserID           uint64         `json:"user_id"`
	UserEmail        string         `json:"user_email"`
	Status           string         `json:"status"`
	TotalAmountMinor int64          `json:"total_amount_minor"`
	Currency         string         `json:"currency"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ItemCount        int64          `json:"item_count"`
	ItemsSummary     sql.NullString `json:"items_summary"`
}

func (q *Queries) AdminListOrders(ctx context.Context) ([]AdminListOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOrdersRow{}
	for rows.Next() {
		var i AdminListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.UserEmail,
			&i.Status,
			&i.TotalAmountMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
			&i.ItemsSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRecentOrders = `-- name: AdminListRecentOrders :many
SELECT
  o.id,
  o.order_no,
  o.user_id,
  u.email AS user_email,
  o.status,
  o.total_amount_minor,
  o.currency,
  o.created_at,
  o.updated_at,
  COUNT(oi.id) AS item_count,
  GROUP_CONCAT(
    CONCAT(p.title, IF(oi.quantity > 1, CONCAT(' ×', oi.quantity), ''))
    ORDER BY oi.id
    SEPARATOR '、'
  ) AS items_summary
FROM orders o
INNER JOIN users u ON u.id = o.user_id
LEFT JOIN order_items oi ON oi.order_id = o.id
LEFT JOIN products p ON p.id = oi.product_id
GROUP BY o.id, o.order_no, o.user_id, u.email, o.status, o.total_amount_minor, o.currency, o.created_at, o.updated_at
ORDER BY o.created_at DESC, o.id DESC
LIMIT ?
`

func (q *Queries) AdminListRecentOrders(ctx context.Context, limit int32) ([]AdminListOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListRecentOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOrdersRow{}
	for rows.Next() {
		var i AdminListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.UserEmail,
			&i.Status,
			&i.TotalAmountMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
			&i.ItemsSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetOrderByID = `-- name: AdminGetOrderByID :one
SELECT
  o.id,
  o.order_no,
  o.user_id,
  u.email AS user_email,
  o.status,
  o.total_amount_minor,
  o.currency,
  o.created_at,
  o.updated_at
FROM orders o
INNER JOIN users u ON u.id = o.user_id
WHERE o.id = ?
LIMIT 1
`

type AdminGetOrderByIDRow struct {
	ID               uint64    `json:"id"`
	OrderNo          string    `json:"order_no"`
	UserID           uint64    `json:"user_id"`
	UserEmail        string    `json:"user_email"`
	Status           string    `json:"status"`
	TotalAmountMinor int64     `json:"total_amount_minor"`
	Currency         string    `json:"currency"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) AdminGetOrderByID(ctx context.Context, id uint64) (AdminGetOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetOrderByID, id)
	var i AdminGetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.UserEmail,
		&i.Status,
		&i.TotalAmountMinor,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListOrderItems = `-- name: AdminListOrderItems :many
SELECT
  oi.id,
  oi.order_id,
  oi.product_id,
  p.title AS product_title,
  oi.quantity,
  oi.unit_price_minor
FROM order_items oi
INNER JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = ?
ORDER BY oi.id ASC
`

type AdminListOrderItemsRow struct {
	ID              uint64 `json:"id"`
	OrderID         uint64 `json:"order_id"`
	ProductID       uint64 `json:"product_id"`
	ProductTitle    string `json:"product_title"`
	Quantity        uint32 `json:"quantity"`
	UnitPriceMinor  int64  `json:"unit_price_minor"`
}

func (q *Queries) AdminListOrderItems(ctx context.Context, orderID uint64) ([]AdminListOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOrderItemsRow{}
	for rows.Next() {
		var i AdminListOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductTitle,
			&i.Quantity,
			&i.UnitPriceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
