// Code generated by sqlc. DO NOT EDIT.
// source: orders.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders (order_no, user_id, status, total_amount_minor, currency)
VALUES (?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	OrderNo          string
	UserID           uint64
	Status           string
	TotalAmountMinor int64
	Currency         string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder,
		arg.OrderNo,
		arg.UserID,
		arg.Status,
		arg.TotalAmountMinor,
		arg.Currency,
	)
}

const createOrderItem = `-- name: CreateOrderItem :execresult
INSERT INTO order_items (order_id, product_id, quantity, unit_price_minor)
VALUES (?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID        uint64
	ProductID      uint64
	Quantity       uint32
	UnitPriceMinor int64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPriceMinor,
	)
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*) AS count FROM orders WHERE user_id = ?
`

func (q *Queries) CountOrdersByUser(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOrdersByUserPaged = `-- name: ListOrdersByUserPaged :many
SELECT
  o.id,
  o.order_no,
  o.status,
  o.total_amount_minor,
  o.currency,
  o.created_at,
  COUNT(oi.id) AS item_count,
  GROUP_CONCAT(
    CONCAT(p.title, IF(oi.quantity > 1, CONCAT(' ×', oi.quantity), ''))
    ORDER BY oi.id
    SEPARATOR '、'
  ) AS items_summary
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
LEFT JOIN products p ON p.id = oi.product_id
WHERE o.user_id = ?
GROUP BY o.id, o.order_no, o.status, o.total_amount_minor, o.currency, o.created_at
ORDER BY o.created_at DESC, o.id DESC
LIMIT ? OFFSET ?
`

type ListOrdersByUserPagedRow struct {
	ID               uint64         `json:"id"`
	OrderNo          string         `json:"order_no"`
	Status           string         `json:"status"`
	TotalAmountMinor int64          `json:"total_amount_minor"`
	Currency         string         `json:"currency"`
	CreatedAt        time.Time      `json:"created_at"`
	ItemCount        int64          `json:"item_count"`
	ItemsSummary     sql.NullString `json:"items_summary"`
}

func (q *Queries) ListOrdersByUserPaged(ctx context.Context, userID uint64, limit int32, offset int32) ([]ListOrdersByUserPagedRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUserPaged, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByUserPagedRow{}
	for rows.Next() {
		var i ListOrdersByUserPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.Status,
			&i.TotalAmountMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.ItemCount,
			&i.ItemsSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getOrderHeaderForUser = `-- name: GetOrderHeaderForUser :one
SELECT
  o.id,
  o.order_no,
  o.user_id,
  o.status,
  o.total_amount_minor,
  o.currency,
  o.created_at
FROM orders o
WHERE o.id = ? AND o.user_id = ?
LIMIT 1
`

type GetOrderHeaderForUserRow struct {
	ID               uint64    `json:"id"`
	OrderNo          string    `json:"order_no"`
	UserID           uint64    `json:"user_id"`
	Status           string    `json:"status"`
	TotalAmountMinor int64     `json:"total_amount_minor"`
	Currency         string    `json:"currency"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) GetOrderHeaderForUser(ctx context.Context, id uint64, userID uint64) (GetOrderHeaderForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderHeaderForUser, id, userID)
	var i GetOrderHeaderForUserRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.TotalAmountMinor,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT
  oi.id,
  oi.order_id,
  oi.product_id,
  p.slug AS product_slug,
  p.title AS product_title,
  p.preview_url AS product_preview_url,
  p.image_url AS product_image_url,
  oi.quantity,
  oi.unit_price_minor
FROM order_items oi
INNER JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = ?
ORDER BY oi.id ASC
`

type ListOrderItemsByOrderIDRow struct {
	ID                 uint64         `json:"id"`
	OrderID            uint64         `json:"order_id"`
	ProductID          uint64         `json:"product_id"`
	ProductSlug        string         `json:"product_slug"`
	ProductTitle       string         `json:"product_title"`
	ProductPreviewUrl  sql.NullString `json:"product_preview_url"`
	ProductImageUrl    sql.NullString `json:"product_image_url"`
	Quantity           uint32         `json:"quantity"`
	UnitPriceMinor     int64          `json:"unit_price_minor"`
}

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uint64) ([]ListOrderItemsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i ListOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductSlug,
			&i.ProductTitle,
			&i.ProductPreviewUrl,
			&i.ProductImageUrl,
			&i.Quantity,
			&i.UnitPriceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateOrderStatusByID = `-- name: UpdateOrderStatusByID :execrows
UPDATE orders SET status = ? WHERE id = ? AND status = ?
`

func (q *Queries) UpdateOrderStatusByID(ctx context.Context, newStatus string, id uint64, oldStatus string) (int64, error) {
	res, err := q.db.ExecContext(ctx, updateOrderStatusByID, newStatus, id, oldStatus)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

const payOrderIfPending = `-- name: PayOrderIfPending :execrows
UPDATE orders SET status = 'paid' WHERE id = ? AND user_id = ? AND status = 'pending'
`

func (q *Queries) PayOrderIfPending(ctx context.Context, id uint64, userID uint64) (int64, error) {
	res, err := q.db.ExecContext(ctx, payOrderIfPending, id, userID)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
