// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: password_reset.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :execresult
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	UserID    uint64    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
}

const getValidPasswordResetToken = `-- name: GetValidPasswordResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token_hash = ?
  AND used_at IS NULL
  AND expires_at > UTC_TIMESTAMP()
LIMIT 1
`

type PasswordResetToken struct {
	ID        uint64       `json:"id"`
	UserID    uint64       `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

func (q *Queries) GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getValidPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used_at = UTC_TIMESTAMP()
WHERE id = ?
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, id)
	return err
}
