// Code generated by sqlc. DO NOT EDIT.
// versions:
// sqlc v1.29.0
// source: products_admin.sql

package db

import (
	"context"
	"database/sql"
)

const adminCreateProduct = `-- name: AdminCreateProduct :execresult
INSERT INTO products (slug, category, title, description, price_minor, currency, image_url, preview_url, download_url, sort_order, recommended, visible, downloads, score)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AdminCreateProductParams struct {
	Slug        string         `json:"slug"`
	Category    string         `json:"category"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	PriceMinor  int64          `json:"price_minor"`
	Currency    string         `json:"currency"`
	ImageUrl    sql.NullString `json:"image_url"`
	PreviewUrl  sql.NullString `json:"preview_url"`
	DownloadUrl sql.NullString `json:"download_url"`
	SortOrder   int32          `json:"sort_order"`
	Recommended bool           `json:"recommended"`
	Visible     bool           `json:"visible"`
	Downloads   int64          `json:"downloads"`
	Score       float64        `json:"score"`
}

func (q *Queries) AdminCreateProduct(ctx context.Context, arg AdminCreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, adminCreateProduct,
		arg.Slug,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.PriceMinor,
		arg.Currency,
		arg.ImageUrl,
		arg.PreviewUrl,
		arg.DownloadUrl,
		arg.SortOrder,
		arg.Recommended,
		arg.Visible,
		arg.Downloads,
		arg.Score,
	)
}

const adminDeleteProduct = `-- name: AdminDeleteProduct :exec
DELETE FROM products
WHERE id = ?
`

func (q *Queries) AdminDeleteProduct(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, adminDeleteProduct, id)
	return err
}

const adminGetProductByID = `-- name: AdminGetProductByID :one
SELECT id, slug, category, title, description, price_minor, currency, image_url, preview_url, download_url, sort_order, recommended, visible, downloads, score, created_at
FROM products
WHERE id = ?
LIMIT 1
`

func (q *Queries) AdminGetProductByID(ctx context.Context, id uint64) (Product, error) {
	row := q.db.QueryRowContext(ctx, adminGetProductByID, id)
	var i Product
	err := row.Scan(scanProductFields(&i)...)
	return i, err
}

const adminGetProductBySlug = `-- name: AdminGetProductBySlug :one
SELECT id, slug, category, title, description, price_minor, currency, image_url, preview_url, download_url, sort_order, recommended, visible, downloads, score, created_at
FROM products
WHERE slug = ?
LIMIT 1
`

func (q *Queries) AdminGetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRowContext(ctx, adminGetProductBySlug, slug)
	var i Product
	err := row.Scan(scanProductFields(&i)...)
	return i, err
}

const adminListProducts = `-- name: AdminListProducts :many
SELECT id, slug, category, title, description, price_minor, currency, image_url, preview_url, download_url, sort_order, recommended, visible, downloads, score, created_at
FROM products
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) AdminListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, adminListProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(scanProductFields(&i)...); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateProduct = `-- name: AdminUpdateProduct :exec
UPDATE products
SET slug = ?, category = ?, title = ?, description = ?, price_minor = ?, currency = ?, image_url = ?, preview_url = ?, download_url = ?, sort_order = ?, recommended = ?, visible = ?, downloads = ?, score = ?
WHERE id = ?
`

type AdminUpdateProductParams struct {
	Slug        string         `json:"slug"`
	Category    string         `json:"category"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	PriceMinor  int64          `json:"price_minor"`
	Currency    string         `json:"currency"`
	ImageUrl    sql.NullString `json:"image_url"`
	PreviewUrl  sql.NullString `json:"preview_url"`
	DownloadUrl sql.NullString `json:"download_url"`
	SortOrder   int32          `json:"sort_order"`
	Recommended bool           `json:"recommended"`
	Visible     bool           `json:"visible"`
	Downloads   int64          `json:"downloads"`
	Score       float64        `json:"score"`
	ID          uint64         `json:"id"`
}

func (q *Queries) AdminUpdateProduct(ctx context.Context, arg AdminUpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, adminUpdateProduct,
		arg.Slug,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.PriceMinor,
		arg.Currency,
		arg.ImageUrl,
		arg.PreviewUrl,
		arg.DownloadUrl,
		arg.SortOrder,
		arg.Recommended,
		arg.Visible,
		arg.Downloads,
		arg.Score,
		arg.ID,
	)
	return err
}

const adminCountOrderItemsByProduct = `-- name: AdminCountOrderItemsByProduct :one
SELECT COUNT(*) AS count FROM order_items WHERE product_id = ?
`

func (q *Queries) AdminCountOrderItemsByProduct(ctx context.Context, productID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountOrderItemsByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminSetProductRecommended = `-- name: AdminSetProductRecommended :exec
UPDATE products SET recommended = ? WHERE id = ?
`

func (q *Queries) AdminSetProductRecommended(ctx context.Context, recommended bool, id uint64) error {
	_, err := q.db.ExecContext(ctx, adminSetProductRecommended, recommended, id)
	return err
}

const adminSetProductVisible = `-- name: AdminSetProductVisible :exec
UPDATE products SET visible = ? WHERE id = ?
`

func (q *Queries) AdminSetProductVisible(ctx context.Context, visible bool, id uint64) error {
	_, err := q.db.ExecContext(ctx, adminSetProductVisible, visible, id)
	return err
}
