// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AdminCountOrders(ctx context.Context) (int64, error)
	AdminCountOrdersByStatus(ctx context.Context, status string) (int64, error)
	AdminCountOrdersToday(ctx context.Context) (int64, error)
	AdminCountOrdersYesterday(ctx context.Context) (int64, error)
	AdminCountBusiness(ctx context.Context) (int64, error)
	AdminCountBusinessBySection(ctx context.Context, sectionSlug string) (int64, error)
	AdminCountOrdersByUser(ctx context.Context, userID uint64) (int64, error)
	AdminCountOrdersFiltered(ctx context.Context, arg AdminOrdersFilterArgs) (int64, error)
	AdminCountProducts(ctx context.Context) (int64, error)
	AdminCountProductsFiltered(ctx context.Context, arg AdminProductsFilterArgs) (int64, error)
	AdminCountUsers(ctx context.Context) (int64, error)
	AdminCountUsersFiltered(ctx context.Context, query string, userNoQuery string) (int64, error)
	AdminCountUsersToday(ctx context.Context) (int64, error)
	AdminCountUsersYesterday(ctx context.Context) (int64, error)
	AdminDailyNewOrders(ctx context.Context) ([]AdminDailyNewOrdersRow, error)
	AdminDailyNewOrdersSince(ctx context.Context, intervalDays int32) ([]AdminDailyNewOrdersRow, error)
	AdminDailyNewUsers(ctx context.Context) ([]AdminDailyNewUsersRow, error)
	AdminDailyNewUsersSince(ctx context.Context, intervalDays int32) ([]AdminDailyNewUsersRow, error)
	AdminGetBusinessSection(ctx context.Context, slug string) (BusinessSection, error)
	AdminGetDoc(ctx context.Context, slug string) (Doc, error)
	AdminListBusinessSections(ctx context.Context) ([]BusinessSection, error)
	AdminListDocs(ctx context.Context) ([]AdminListDocsRow, error)
	AdminCreateBusiness(ctx context.Context, arg AdminCreateBusinessParams) (sql.Result, error)
	AdminCreateProduct(ctx context.Context, arg AdminCreateProductParams) (sql.Result, error)
	AdminDeleteBusiness(ctx context.Context, id uint64) error
	AdminDeleteProduct(ctx context.Context, id uint64) error
	AdminGetBusinessByID(ctx context.Context, id uint64) (Business, error)
	AdminGetProductByID(ctx context.Context, id uint64) (Product, error)
	AdminGetProductBySlug(ctx context.Context, slug string) (Product, error)
	AdminGetUserByID(ctx context.Context, id uint64) (AdminListUsersRow, error)
	AdminGetOrderByID(ctx context.Context, id uint64) (AdminGetOrderByIDRow, error)
	AdminListBusiness(ctx context.Context) ([]Business, error)
	AdminListBusinessBySection(ctx context.Context, sectionSlug string) ([]Business, error)
	AdminListBusinessBySectionPaged(ctx context.Context, sectionSlug string, limit int32, offset int32) ([]Business, error)
	AdminListBusinessPaged(ctx context.Context, limit int32, offset int32) ([]Business, error)
	AdminListOrderItems(ctx context.Context, orderID uint64) ([]AdminListOrderItemsRow, error)
	AdminListOrders(ctx context.Context) ([]AdminListOrdersRow, error)
	AdminListOrdersPaged(ctx context.Context, limit int32, offset int32) ([]AdminListOrdersRow, error)
	AdminListOrdersByUserPaged(ctx context.Context, userID uint64, limit int32, offset int32) ([]AdminListOrdersRow, error)
	AdminListOrdersFilteredPaged(ctx context.Context, arg AdminOrdersFilterArgs, limit int32, offset int32) ([]AdminListOrdersRow, error)
	AdminListProducts(ctx context.Context) ([]Product, error)
	AdminListProductsFilteredPaged(ctx context.Context, arg AdminProductsFilterArgs, limit int32, offset int32) ([]Product, error)
	AdminListProductsPaged(ctx context.Context, limit int32, offset int32) ([]Product, error)
	AdminListRecentOrders(ctx context.Context, limit int32) ([]AdminListOrdersRow, error)
	AdminListUsers(ctx context.Context) ([]AdminListUsersRow, error)
	AdminListUsersFilteredPaged(ctx context.Context, query string, userNoQuery string, limit int32, offset int32) ([]AdminListUsersRow, error)
	AdminListUsersPaged(ctx context.Context, limit int32, offset int32) ([]AdminListUsersRow, error)
	AdminSumPaidAmount(ctx context.Context) (int64, error)
	AdminTopProductSales(ctx context.Context) ([]AdminTopProductSalesRow, error)
	AdminTopProductSalesSince(ctx context.Context, intervalDays int32) ([]AdminTopProductSalesRow, error)
	AdminUpdateBusiness(ctx context.Context, arg AdminUpdateBusinessParams) error
	AdminUpdateBusinessSection(ctx context.Context, arg AdminUpdateBusinessSectionParams) error
	AdminUpdateNickname(ctx context.Context, nickname string, id uint64) error
	AdminUpdatePassword(ctx context.Context, passwordHash string, id uint64) error
	AdminUpdateProduct(ctx context.Context, arg AdminUpdateProductParams) error
	UserOwnsPaidProduct(ctx context.Context, arg UserOwnsPaidProductParams) (bool, error)
	CountOrdersByUser(ctx context.Context, userID uint64) (int64, error)
	ClearCartByUser(ctx context.Context, userID uint64) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetAdminByAccount(ctx context.Context, account string) (Admin, error)
	GetAdminByID(ctx context.Context, id uint64) (Admin, error)
	GetCartItemByUserProduct(ctx context.Context, arg GetCartItemByUserProductParams) (CartItem, error)
	GetProductByID(ctx context.Context, id uint64) (Product, error)
	GetProductByIDInternal(ctx context.Context, id uint64) (Product, error)
	GetDocBySlug(ctx context.Context, slug string) (Doc, error)
	GetOrderHeaderForUser(ctx context.Context, id uint64, userID uint64) (GetOrderHeaderForUserRow, error)
	GetSiteContent(ctx context.Context, contentKey string) (SiteContent, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uint64) (User, error)
	GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) (sql.Result, error)
	ListBusinessBySection(ctx context.Context, sectionSlug string) ([]Business, error)
	ListBusinessSections(ctx context.Context) ([]BusinessSection, error)
	ListCartItemsByUser(ctx context.Context, userID uint64) ([]ListCartItemsByUserRow, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID uint64) ([]ListOrderItemsByOrderIDRow, error)
	ListOrdersByUserPaged(ctx context.Context, userID uint64, limit int32, offset int32) ([]ListOrdersByUserPagedRow, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsByCategory(ctx context.Context, category string) ([]Product, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id uint64) error
	Ping(ctx context.Context) (int32, error)
	PayOrderIfPending(ctx context.Context, id uint64, userID uint64) (int64, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (int64, error)
	UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) error
	UpdateOrderStatusByID(ctx context.Context, newStatus string, id uint64, oldStatus string) (int64, error)
	UpsertDoc(ctx context.Context, slug string, title string, markdown string) error
	UpsertSiteContent(ctx context.Context, contentKey string, contentJSON []byte) error
}

var _ Querier = (*Queries)(nil)
