// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users_admin.sql

package db

import (
	"context"
	"time"
)

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, user_no, email, created_at
FROM users
ORDER BY id DESC
`

type AdminListUsersRow struct {
	ID        uint64    `json:"id"`
	UserNo    string    `json:"user_no"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AdminListUsers(ctx context.Context) ([]AdminListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(&i.ID, &i.UserNo, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetUserByID = `-- name: AdminGetUserByID :one
SELECT id, user_no, email, created_at
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) AdminGetUserByID(ctx context.Context, id uint64) (AdminListUsersRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetUserByID, id)
	var i AdminListUsersRow
	err := row.Scan(&i.ID, &i.UserNo, &i.Email, &i.CreatedAt)
	return i, err
}
