// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (user_no, email, password_hash)
VALUES (?, ?, ?)
`

type CreateUserParams struct {
	UserNo       string `json:"user_no"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.UserNo, arg.Email, arg.PasswordHash)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_no, email, password_hash, created_at
FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserNo,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_no, email, password_hash, created_at
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserNo,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const userUpdatePassword = `-- name: UserUpdatePassword :exec
UPDATE users
SET password_hash = ?
WHERE id = ?
`

type UserUpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           uint64 `json:"id"`
}

func (q *Queries) UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, userUpdatePassword, arg.PasswordHash, arg.ID)
	return err
}
